name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack start notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: plantit-dev
          SLACK_ICON: https://raw.githubusercontent.com/Computational-Plant-Science/spg/master/rosette_logo.jpg
          SLACK_MESSAGE: 'Build started'
          SLACK_TITLE: "Smart Plant Growth: Leaf Segmentation & Traits"
          SLACK_USERNAME: spg
  publish:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          # python
          python -m pip install --upgrade pip
          pip install flake8 pytest coveralls setuptools wheel twine
          pip install -e .
      - name: Publish package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & publish container
        run: |
          docker build -t computationalplantscience/spg -f Dockerfile .
          docker push computationalplantscience/spg
      - name: Slack success notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: plantit-dev
          SLACK_ICON: https://raw.githubusercontent.com/Computational-Plant-Science/spg/master/rosette_logo.jpg
          SLACK_MESSAGE: 'Build succeeded'
          SLACK_TITLE: 'Smart Plant Growth: Leaf Segmentation & Traits'
          SLACK_USERNAME: spg